apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: elastic
spec:
  version: 7.2.0
  http:
    service:
      spec:
        type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master
    count: 1
    podTemplate:
      spec:
       containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: "-Xms4g -Xmx4g"
          resources:
            requests:
              cpu: 4
              memory: 14Gi
            limits:
              memory: 14Gi
              cpu: 4  
       initContainers:              
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true      
#       affinity:
#           nodeAffinity:
#             requiredDuringSchedulingIgnoredDuringExecution:
#               nodeSelectorTerms:
#               - matchExpressions:
#                 - key: failure-domain.beta.kubernetes.io/zone
#                   operator: In
#                   values:
#                   - zone-0                        
    config:   
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      xpack.security.authc.realms:
        native:
          native1:
            order: 1     
      node.master: true
      node.data: false
      node.ingest: false
      cluster.routing.allocation.awareness.attributes: zone  
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: local-storage
          resources:
            requests:
              storage: 15Gi
  - name: zone-1
    count: 2 
    config:   
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      xpack.security.authc.realms:
        native:
          native1:
            order: 1
      node.master: false
      node.data: true
      node.ingest: true
      node.attr.zone: zone-1
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
       spec:
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: "-Xms8g -Xmx8g"
          resources:
            requests:
              cpu: 8
              memory: 30Gi
            limits:
              memory: 30Gi
              cpu: 8
        initContainers:              
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true                                                 
        affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: failure-domain.beta.kubernetes.io/zone
                   operator: In
                   values:
                   - zone-1
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: local-storage
          resources:
            requests:
              storage: 15Gi
  - name: zone-2
    count: 2
    config:
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      xpack.security.authc.realms:
        native:
          native1:
            order: 1
      node.master: false
      node.data: true
      node.ingest: true
      node.attr.zone: zone-2
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: "-Xms8g -Xmx8g"
          resources:
            requests:
              cpu: 8
              memory: 30Gi
            limits:
              memory: 30Gi
              cpu: 8
        initContainers:              
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true                     
        affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: failure-domain.beta.kubernetes.io/zone
                   operator: In
                   values:
                   - zone-2
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: local-storage
          resources:
            requests:
              storage: 15Gi
  - name: zone-3
    count: 2
    config:
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      xpack.security.authc.realms:
        native:
          native1:
            order: 2
      node.master: false
      node.data: true
      node.ingest: true
      node.attr.zone: zone-3
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: "-Xms8g -Xmx8g"
          resources:
            requests:
              cpu: 8
              memory: 30Gi
            limits:
              memory: 30Gi
              cpu: 8
        initContainers:              
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true                 
        affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: failure-domain.beta.kubernetes.io/zone
                   operator: In
                   values:
                   - zone-3
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: local-storage
          resources:
            requests:
              storage: 15Gi


